### ISSUE TITLE
Include Msgpack as requirement - Discussion

### ISSUE THREAD

**Issue by Lnaden** [MolSSI/QCElemental#112]
Do we include Msgpack a requirement, even though its technically optional?

cc conda-forge/qcelemental-feedstock#19

**Comment by loriab** [comment]
* in setup.py, no, as it's optional and this is the general build formula, not a build instance
* in conda package for deps in general, no, as one wants to remain slim, and this is optional
* in conda package for "free" deps (no add'l deps), maybe, if dep has broad utility. (certainly I was vexed in the days when conda `git` was built w/o perl)

**Comment by loriab** [comment]
I have thought better of this. Requirements should be true requirements.
