### ISSUE TITLE
Testing utilities

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCElemental#15]
I was adding some features to Engine and it occurred to me that some testing features are quite useful in the ecosystem such as this [CLI testing tool](https://github.com/MolSSI/QCFractal/blob/master/qcfractal/testing.py#L229). What do we think about adding several testing utilities here that do _not_ depend on libraries outside of standard Python.

I worry a bit that QCElemental will become a general dumping ground if we keep adding things here arbitrarily however. Too many modules is problematic, too few that do too many things is also an issue. Where do we draw the line?

If possible I would like to keep the depends of the library as the following:
 - NumPy
 - Pint
 - pydantic

to keep the footprint pretty small.

**Comment by loriab** [comment]
On this topic, I need `utils` and `compare_utils` from https://github.com/MolSSI/QCElemental/tree/master/qcelemental/tests in qcengine. even though qcng needs qcel, those files aren't properly part of the module or importable. thoughts on whether I should
- (a) copy 'em over
- (b) add a `qcelemental/tests/__init__.py` so potentially importable
- (c) more formally add a testing tools module incl. some of the utilities you mentioned above. (this is probably a non-starter, since I just recalled these files are where the `deepdiff` dep resides.)

**Comment by dgasmith** [comment]
A few notes here:
1) I would prefer a `QCElemental/testing.py` module (a single one even if it is long)
2) I am happy to write a deepdiff replacement, quite straightforward code.
3) Move the testing code to raise normal `ValueError`s or similar.

Lets simplify the compare routines down to:
 - `compare` (for all `==` operations)
 - `compare_float` (for all float and array operations)
 - `compare_dict` (for all dictionary operations)
 -  `compare_molecule_records`

**Comment by dgasmith** [comment]
I would be up for having the compare function return bools similar to [NumPy](https://github.com/numpy/numpy/blob/master/numpy/core/tests/test_einsum.py)'s (allclose, equal, etc). If not, we can skip the inversion and I can work it into a single file.

The idea here with a `testing.py` is to _stop_ copying it between codes and simply inherit for the QCEl one.

If this will be used outside of QCEl (and it will) `QCElemental/qcelemental/testing.py` is the preferred way to do it. `from qcelemental.testing import compare, compare_float, ...`.

**Comment by loriab** [comment]
I think that's a sound strategy. T/F the compares. Down to one file. I'll write a new set of little wrappers for psi4 (raise exceptions if needed and adjust the names (don't think we can spring a global rename on them)) and everything can import from qcel. will plan on this when deepdiff replacement available.

Do you really dislike plural? Could collapse _floats, _arrays, _integers into `compare_values` with `digits=None` that throws if `digits` not passed for non-ints/bools/str.

Later ...

On the deepdiff problem, while I understand the desire for one file, the CLI tools that started this issue may have handy imports that e.g., psi4 doesn't want to depend on. Could do testing as a hidden submodule.

```
QCElemental/qcelemental/  # everything below under this
__init__.py               # do NOT import testing
testing/__init__.py       # import all subsequent
testing/compares.py       # compare_values and everything w/o deepdiff
testing/comparedicts.py   # compare_* that depend on deepdiff
testing/cli.py            # testing tools that may depend on other obscure stuff
```

**Comment by dgasmith** [comment]
What CLI tools did you have issues with? The Python 3.6 sub processing module seems to be quite good these days. I think anything that goes into this testing module would be pretty canonical and I do not want to increase the current dependancies. I would vote that the `__init__` does import testing, but may leave off specific modules who have very high requirements.

**Comment by dgasmith** [comment]
- I might have misunderstood you on the `subprocess` CLI tools in your last comment. We can move everything into `testing.py` now with the current level of `ModuleNotFoundError` protection that we have I believe so that we can use it in qcng.
 - I like `compare` and `compare_values` where `compare` is just a `==` and `compare_values` uses a NumPy style `atol`/`rtol`.
 - I originally fought contest.py for a bit, but seem to have worked in out in QCFractal. I forget the exact steps, but is doable.
 - Roger that.

**Comment by loriab** [comment]
Debate resolved and `qcel.testing` spreading, imo.
