### ISSUE TITLE
Native Molecule Hashing

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCElemental#154]
**Is your feature request related to a problem? Please describe.**
`mol1 == mol2` should use `get_hash()` not whatever comparison is native to Pydantic.

**Describe the solution you'd like**
Override `__hash__` in Molecule to call `get_hash()` and maybe deprecate that function so that `hash(Molecule)` works just as well.

@mattwelborn

**Comment by mattwelborn** [comment]
Is there any weirdness that could happen here? For example in Fractal, when we record a geometry optimization with tight convergence thresholds, will the last steps all end up in the molecules table? Or will they be seen as

**Comment by dgasmith** [comment]
This relates to #89. There will be a field saying that Molecules cannot be hashed and therefore cannot be compared.

We do see sometimes with `geometric` where we get the same molecule in the optimization trajectory. It is rare, but does happen due to our thresholds.

**Comment by mattwelborn** [comment]
Overring `__hash__ ` has two issues:
1) `__hash__` must return an integer
2) "hash() truncates the value returned from an object’s custom __hash__() method to the size of a Py_ssize_t. This is typically 8 bytes on 64-bit builds and 4 bytes on 32-bit builds."

We could make get_hash return our current hashes and `__hash__` cast it to an integer, but I prefer to just change `__eq__` to use `get_hash()` and not deprecate `get_hash()`

Another issue is whether `compare` should be deprecated.
