### ISSUE TITLE
Result --> SingleResult

### ISSUE THREAD

**Issue by loriab** [MolSSI/QCElemental#155]
So we've got
* `OptimizationInput`/`Optimization`
* `ResultInput`/`Result`

And in another project, I've got the potential for
* `FindifResultInput`/`FindifResult`
* `CBSResultInput`/`CBSResult`

etc. The optimization pair doesn't particularly signal "schema" to me. And it might be convenient to distinguish between the set of `*ResultInput`/`*Result` pairs and the particular energy/gradient/hessian calc that `ResultInput`/`Result` now represents.

It is suggested that the two first items above become the below so that the `*` of `*ResultInput`/`*Result` is never the empty string.
* `OptimizationResultInput`/`OptimizationResult`
* `SingleResultInput`/`SingleResult` (`AnalyticResult`?)

Please weigh in on this change, even if it's just an up/down emoji response.

**Comment by mattwelborn** [comment]
@dgasmith Does this proposal interact at all with plans to make optimization a service?

**Comment by dgasmith** [comment]
@mattwelborn Nope, no changes from me.

Another option is to do:
 - `OptimizationInput / Optimization`
 - `SingleResultInput / SingleResult`
 - ...

Since these names are going to be typed many times I would be hesitant to make them too long. 
`FindifInput/Findif`, `CBSInput/CBS`

**Comment by jchodera** [comment]
I'm with @dgasmith here: It's clearer to use `XInput/XResult`, or perhaps even `XInput/XOutput`. `ResultInput` is syntactically painful.

**Comment by loriab** [comment]
I've thought `ResultInput` a pleasing quirk because you could search for `CBSResult` and hit both input and output stages. But sure, I don't mind `XInput/XResult`. It's searchable and predictable (latter not the case at present). 

So any votes among the below? I'm plenty happy with SingleResult. It's distinctive but with a vague enough definition to not feel wrong stretching it.
* `SingleResult`
* `AnalyticResult`
* `PrimaryResult`
* `AtomicResult`

**Comment by dgasmith** [comment]
`QuantumResult` for the word play, both *a* quantum unit and a quantum chemistry one. I will see myself out...

**Comment by dgasmith** [comment]
`QuantaResult`?

**Comment by loriab** [comment]
Going with `SingleResult`/`SingleInput` and `OptimizationResult`/`OptimizationInput`? I get the feeling `ResultInput` is not well loved. My second-favorite for `SingleResult` is `AtomicResult`, which also makes a nice play on words, so long as it's not mistaken for single-atom result.

To drum up opinions, i'll query on a few more alternatives:
- `CBSResult` (currently) or `CompositeResult`
- `FinDifResult` (currently) or `FDMResult` or `FiniteDifferenceResult` or `StencilResult`
- `NBodyResult` (currently) or `MBEResult` or `ManyBodyResult` or `FragmentResult`

**Comment by dotsdl** [comment]
I'm in favor of syntactic simplicity where it can be found, so something like `XInput / XResult` as a convention is something I can get behind. As a relative newcomer to the project wrapping his head around a rapidly-evolving set of tooling, it helps if the names of things give a sense for their structural purpose and place within the landscape.

`ResultInput`, for example, feels like a sign with one label pointing in two directions. It might get you to where you want to go, but you might also scratch your head every time before you get there.

**Comment by dgasmith** [comment]
@dotsdl Any thoughts on `AtomicInput`/`AtomicOutput`?

@mattwelborn Can you weigh in here?

@leeping Any thoughts here? I think your comment here would be quite valuable as you are not too deep into the ecosystem.

**Comment by dgasmith** [comment]
Last round of pinging, I am up for making the change this release with a deprecation warning.

@bennybp @twindus @lothian

**Comment by leeping** [comment]
Thanks for asking; after reading this discussion I think `XInput / XResult` is the more intuitive choice. :)

**Comment by loriab** [comment]
I strongly favor `XInput`/`XResult` over `XInput`/`XOutput`.
I'm for
* `AtomicResult`
* `CBSResult`
* `FDMResult`
* `MBEResult`
* `OptimizationResult`

with second choice
* `SingleResult`
* `CompositeResult`
* `StencilResult`
* `ManyBodyResult`
* `OptimizationResult`

(or any combination thereof)

**Comment by dgasmith** [comment]
What about:
- CompositeResult
- FiniteDifferenceResult
- ManyBodyResult

`FDMResult` and `MBEResult` are hard to understand. `CBSResult` would be an oddity, but is a well known literature description.

**Comment by dgasmith** [comment]
Closed by #167, thank you everyone for the comments and feedback.
