### ISSUE TITLE
Clarify qcelemental/checkup_data/{physconst,periodictable}.py license

### ISSUE THREAD

**Issue by mbanck** [MolSSI/QCElemental#159]
Those two files have a Psi4 license header, is that intended? I guess it makes sense as they might have been copied over from Psi4, but maybe it would be better to check with the Psi4 project whether they/you are fine with relinquishing that copyright and just have it be the top-level `LICENSE.md`?

**Comment by loriab** [comment]
Nothing in that directory gets installed. It's more of a template for other codes to sanity check their local-->qcel transition. Psi4 probably shouldn't have been slapping a license header on those data files in the first place. I'll remove it.
