### ISSUE TITLE
Codecov report combining

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCElemental#175]
At the moment, Codecov reports are not correctly merging resulting in a lower coverage status than is truly available. Unsure why this is as all reports are uploaded correctly, it looks like only the first report is correctly merged.

A small hunch is that the git SHA is not correctly being uploaded from all reports.

**Comment by loriab** [comment]
looks like a GH actions consequence. weren't you seeing a problem with GHA and SHAs in another repo? or was that azure?

**Comment by dgasmith** [comment]
Yes, absolutely a GHA consequence. Travis is a "trusted" CI provider for Codecov so it automatically takes care of a number of issues.

From [Codecov FAQ](https://docs.codecov.io/docs/frequently-asked-questions):
> The upload token is required for all uploads, except originating from public project using Travis-CI, Circle CI, or AppVeyor CI.

See a PR that could fix this [here](https://github.com/codecov/codecov-python/pull/214/files). From this I derive that we may need to (potentially) upload additional data, but isn't commented on [here](https://docs.codecov.io/docs/merging-reports).

**Comment by loriab** [comment]
After #180, codecov has returned to pre-GHA levels, so I think this is resolved. Please reopen if more services communications trouble suspected.
