### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCElemental#178]
**Describe the bug**
Pubchem tests occasionally fail on CI.

**Expected behavior**
Pubchem tests should always pass to ensure CI is stable.

**Additional context**

We could consider a pytest wrapper like the following:

```python
@pytest.mark.flaky(reruns=5)
def test_example():
    import random
    assert random.choice([True, False])
```

From [this](https://github.com/pytest-dev/pytest-rerunfailures/blob/master/pytest_rerunfailures.py) pytest module. Not an overwhelming fan of adding a new test depends, but could help. Also we could make with an `xfail`, but I feel this is dangerous.

**Comment by loriab** [comment]
When pubchem gets busy, it tends to be for a spell longer than the qcel tests, so rerun in quick succession may not help.

**Comment by dgasmith** [comment]
@mattwelborn Maybe time for mock...?

**Comment by loriab** [comment]
Before anyone spends more real time on that unfortunate file, may also want to consider pubchempy.

**Comment by dgasmith** [comment]
I would be up for copying `pubchempy`s single file include with the license as the header.
