### ISSUE TITLE
Allow generation of Fortran include or module file from NIST codata

### ISSUE THREAD

**Issue by awvwgk** [MolSSI/QCElemental#256]
**Is your feature request related to a problem? Please describe.**

The NIST codata available in qcel can currently be exported to a C header, it would be interesting to have an export to a Fortran include or module file as well.

**Describe the solution you'd like**

Have an additional function in https://github.com/MolSSI/QCElemental/blob/master/qcelemental/physical_constants/context.py to export a Fortran include or module file.

**Describe alternatives you've considered**

The C header could be included in Fortran as well since it only contains macro definitions.

**Additional context**

Discussion on parsing NIST codata on the Fortran discourse: https://fortran-lang.discourse.group/t/tips-to-make-this-toy-program-faster/803/38

**Comment by loriab** [comment]
Generating a Fortran header would be a welcome addition. That C header is tailored for Psi4, and the idea was any number of header exporters could be added to bridge btwn the qcel representation and whatever downstream programs need.

**Comment by awvwgk** [comment]
Is there a CI check in this repository of the C header we could replicate in Fortran?

**Comment by loriab** [comment]
Only that it writes, not that it roundtrips. https://github.com/MolSSI/QCElemental/blob/master/qcelemental/tests/test_constants.py#L106-L110

Diff with the existing header has been the sanity/format check. Admittedly not very strong w/o an existing downstream.
