### ISSUE TITLE
CI workflow only enabled for master branch?

### ISSUE THREAD

**Issue by awvwgk** [MolSSI/QCElemental#258]
**Is your feature request related to a problem? Please describe.**

CI workflows are currently limited to the master branch. Is there any particular reason to not run tests on feature branches?

**Describe the solution you'd like**

Enable CI workflow for all branches to enable (easy) testing in forks.

**Comment by loriab** [comment]
I had thought that master/master was triggering on push-to-master and push-to-fork-with-open-PR-to-master, but if you're seeing otherwise, I can revert. This was a recent change, sorry about that. I had been trying to suppress double testing on branches on upstream.

**Comment by awvwgk** [comment]
There may still be a push build, but on the fork, but those are usually opt-in. (Visible) double runs on push and pull_request would only happen for a branch in the repository with a PR against another branch in the same repository.
