### ISSUE TITLE
Add a citation file?

### ISSUE THREAD

**Issue by lilyminium** [MolSSI/QCElemental#282]
**Is your feature request related to a problem? Please describe.**

I would like to cite QCElemental (and related packages) as software I am using, but there seems to be no clear way to do it (e.g. there are 29 contributors on GitHub -- alphabetical ordering of username?)

**Describe the solution you'd like**

Github supports CITATION.cff files, it'd be super helpful for people who want to cite the QC stack to have one.

https://citation-file-format.github.io/

**Describe alternatives you've considered**

**Additional context**

**Comment by loriab** [comment]
good point. qcengine has a codemeta, but qcel does not. I can see about a citation file here and/or a zenodo. for the QC stack, qcarchive as a whole and especially qcfractal have https://wires.onlinelibrary.wiley.com/doi/abs/10.1002/wcms.1491 . qcengine and sort-of qcel have https://aip.scitation.org/doi/pdf/10.1063/5.0059356 . qcschema has nothing journal-wise. i'll see about documenting better, but see if any of those could do in the interim.

**Comment by lilyminium** [comment]
Great, thank you for those links!

**Comment by coltonbh** [comment]
Add a note in `README.md` suggesting to use one of these two papers to cite `QCElemental`
