### ISSUE TITLE
Links to changelogs in releases don't work

### ISSUE THREAD

**Issue by susilehtola** [MolSSI/QCElemental#319]
The links to the changelogs on the GitHub releases page don't work.

For example, for 0.26.0, the changelog link is given as
https://github.com/MolSSI/QCElemental/blob/master/docs/source/changelog.rst#0260--2023-07-31

which gives a 404 - page not found. The correct link is obtained by removing `source/`:
https://github.com/MolSSI/QCElemental/blob/master/docs/changelog.rst#0260--2023-07-31

**Comment by loriab** [comment]
drat, I must have copied the pattern from qcengine, which does have a `source/` in there.

**Comment by loriab** [comment]
Ah, #310 removed the `source/` intermediate dir. Ok, I've fixed the latest two in the GH releases links and will go through the rest.
