### ISSUE TITLE
Molecule representation should include charge and multiplicity

### ISSUE THREAD

**Issue by awvwgk** [MolSSI/QCElemental#330]
**Is your feature request related to a problem? Please describe.**

Currently printing a molecule to a string does not include the charge or multiplicity information

**Describe the solution you'd like**

Instead of printing `Molecule(name="C", formula="C", hash="...")` printing `Molecule(name="C+", formula="2^C+", hash="...")` would be preferred. Singlet multiplicity could be omitted from printout

**Describe alternatives you've considered**

Include multiplicity and charge in the string representation.

**Additional context**

**Comment by loriab** [comment]
actually will be fixed by #340
