### ISSUE TITLE
Inconsistent dependency versions for pint and numpy

### ISSUE THREAD

**Issue by TyBalduf** [MolSSI/QCElemental#334]
**Describe the bug**
pyproject.toml has the following version specifications.
```
numpy = [
    { version = ">=1.12.0", python = "3.8" },
    { version = ">=1.26.1", python = ">=3.9,<3.13" },
]
python = "^3.7"
pint = ">=0.10.0"
```
On Python3.11, the default pip installation of qcelemental currently leads to numpy 1.26.4 and I had pint 0.11 installed. Any version of pint prior to 0.21 is incompatible with numpy >1.25 because the `alen` function was removed from numpy.  

**To Reproduce**
1. pip install qcelemental
2. Run anything that requires importing pint. 

`python -c "import qcelemental as qcel; print(qcel.__file__, qcel.__version__)"` --> /my_dir/lib/python3.11/site-packages/qcelemental/__init__.py 0.27.1

**Desired behavior**
The pint installation should have split versioning similar to the numpy dependency. I think this would look like 
```
numpy = [
    { version = ">=1.12.0", python = "3.8" },
    { version = ">=1.26.1", python = ">=3.9,<3.13" },
]
python = "^3.7"
pint =[
    { version = ">=0.10", python = "3.8" },
    { version = ">=0.21", python = ">=3.9,<3.13" },
]
```

**Comment by loriab** [comment]
Thanks for the report and the fix!

closed by #335
