### ISSUE TITLE
Testing complex numbers

### ISSUE THREAD

**Issue by robertodr** [MolSSI/QCElemental#77]
I am using the testing functionality within Psi4 and I am running into this warning when using `compare_arrays`:
```
 /home/roberto/Workspace/robertodr/psi4/build_xtensor/stage/lib/qcelemental/testing.py:106: ComplexWarning: Casting complex values to real discards the imaginary part
  xptd, cptd = np.array(expected, dtype=np.float), np.array(computed, dtype=np.float)
```
for complex numbers this is unwanted, as I'd like to test that both real and imaginary parts are as expected.

I changed that line to:
```
xptd, cptd = np.array(expected, dtype=expected.dtype), np.array(computed, dtype=computed.dtype)
```
though it doesn't seem exactly correct to do this. Probably a check that the types match between expected and computed should be done before checking that the actual values match.

@loriab suggested getting rid of this line https://github.com/MolSSI/QCElemental/blob/master/qcelemental/datum.py#L47 but the warning still pops up.

**Comment by loriab** [comment]
maybe:
```
if expected.dtype == np.complex:
    dtype = np.complex
else:
    dtype = np.float
xptd, cptd = np.array(expected, dtype=dtype), np.array(computed, dtype=dtype)
```

something like that should both better handle complex case and still do the expected coercion.

**Comment by loriab** [comment]
Note that with #85, provided one has `msgpack` installed (which we could make a req'd dep for psi4,  while staying optional for qcel), all numpy arrays stay as their native type upon serialization, so complex should be fine and not a json repr issue needing addressing here or in pydantic.

**Comment by robertodr** [comment]
I reply a bit late. I have updated QCElemental to v0.6.1 and installed MsgPack in my dev environment. I still see the `ComplexWarning`, is there something more I should do on my end?

**Comment by robertodr** [comment]
@loriab any additional hints on how to fix this?

**Comment by dgasmith** [comment]
@loriab's suggested change seems like it would work. Looks like the relevant code is [here](https://github.com/MolSSI/QCElemental/blob/master/qcelemental/testing.py#L105). Could you give it a shot?

**Comment by robertodr** [comment]
Yup, that did it!

**Comment by dgasmith** [comment]
Awesome, please do make a PR to get this in.
