### ISSUE TITLE
Some elements missing in /util

### ISSUE THREAD

**Issue by victorandscience** [MolSSI/QCElemental#79]
Tried to import QCElemental/models/molecule.py but I got a complaint since it's not being able to find  **measure_coordinates, provenance_stamp and which_import** which are not located in the util folder.

**Comment by Lnaden** [comment]
Can you elaborate more on how you installed QCElemental and can you post a minimal example of how you did the import (with the error if you could)?

**Comment by victorandscience** [comment]
I first used pip, and then manually clone it to the python packages folder. Had the same problem with both. 

**Imported as:** 

`import qcelemental as qcel`

**Tried to run:**

`mol = qcel.models.Molcule.from_file("bent.xyz")`


**Got as output**

AttributeError                            Traceback (most recent call last)
<ipython-input-19-e203df466e2f> in <module>()
      8 """)
      9 
---> 10 mol = qcel.models.Molcule.from_file("bent.xyz")
     11 
     12 

AttributeError: module 'qcelemental' has no attribute 'models'


---------------------------------------------------------------------------

**Imported as** 
`from qcelemental.models import Molecule`

**to get the output:**

ImportError                               Traceback (most recent call last)
<ipython-input-21-dc5835960c8e> in <module>()
      8 
      9 #import qcelemental as qcel
---> 10 from qcelemental.models import Molecule

/anaconda3/lib/python3.6/site-packages/qcelemental/models/__init__.py in <module>()
      5                       "`conda install pydantic -c conda-forge` or `pip install pydantic`")
      6 
----> 7 from .molecule import Molecule
      8 from .results import Result, ResultInput, ResultProperties
      9 from .procedures import OptimizationInput, Optimization

/anaconda3/lib/python3.6/site-packages/qcelemental/models/molecule.py in <module>()
     17 from ..physical_constants import constants
     18 from ..testing import compare, compare_values
---> 19 from ..util import measure_coordinates, provenance_stamp, which_import
     20 
     21 # Rounding quantities for hashing

ImportError: cannot import name 'measure_coordinates'

**Comment by loriab** [comment]
check `Molecule` spelling is only typo in post, not your code.

**Comment by victorandscience** [comment]
I apologize. Typo was only in post.

**Comment by Lnaden** [comment]
I can't reproduce this locally.

```bash
conda create -n qcetest -c conda-forge --yes python
conda activate qcetest
pip install qcelemental
```
```python
>>> import qcelemental as qcel
>>>  mol = qcel.models.Molecule.from_file("water.xyz") . # I have a local H2O molecule file
>>>
```

What version are you using of qcelemental are you using? 

Also the fact that your traceback is showing the following lines:
```
/anaconda3/lib/python3.6/site-packages/qcelemental/models/init.py in ()
5 "conda install pydantic -c conda-forge or pip install pydantic")
```
leads me to believe something else is throwing the error or there is a conflict of installations and its not being handled correctly. Can you do a `conda list` and show your installed packages?

**Comment by victorandscience** [comment]
QCElemental's version is 0.42
Attached is a file with the installed packages. 

[packages.txt](https://github.com/MolSSI/QCElemental/files/3346717/packages.txt)

**Comment by Lnaden** [comment]
Thanks for the packages list. There is nothing in there which suggests that there is a conflicting package, but there are a couple of things which are odd.

There are 2 errors here which give me pause, 

the first is that the error `AttributeError: module 'qcelemental' has no attribute 'models'` should only be thrown from version 0.1.3 or sooner, as 0.1.4 added that feature in. 

The second error is the ` from ..util import measure_coordinates, provenance_stamp, which_import` which should have been unreachable in the first place if the first error held. Setting that aside, this was added in v0.2.4.

Given the two items above, the import actions are behaving like there are different QCElementals installed somewhere in the path and its trying to pull from both of them. So I have a few things I would like to ask you to check:
1. Can you look in `/anaconda3/lib/python3.6/site-packages` to make sure there is only the one `qcelemental*` object (may be an .egg or some other folder)?
2. Are you running the imports from a folder which has a copy of the `qcelemental` package in it?
3. Can you create a new conda environment and do a fresh install of the qcelemental package in there (mindful of the 2nd point on this list)?
4. Can you try to do a `import qcelemental` and `qcelemental.__file__`? If that throws an import error, let us know the full stack of the error if you can too.

Finally, can you post your code blocks around triple back ticks? It will help format it much cleaner here on the issue.

Thanks in advance!

**Comment by loriab** [comment]
If you've ever compiled Psi4 from source, it will install its own qcel and/or qcng if it doesn't detect a new enough version. If your `qcelemental.__file__` shows this likely, you can `rm -rf <psi4_clone>/objdir/stage/lib/qce*` to force it to use the conda environment versions.

Ignore if you've no psi4 or psi4 from conda. This is just a common gotcha when qcel/qcng seems to act irrationally.

**Comment by Lnaden** [comment]
There is a psi4 install, so that might be it then

**Comment by loriab** [comment]
If that psi4 install absolutely must be kept working at exactly that version, you want to be careful about blowing away its qcengine. 0.6.4 engine and older-than-~2-weeks psi4 are compatible and 0.7 engine and master psi4 are compatible, but in-between there was a file moved. qcel afaik is freely upgradeable. easiest is to update everything.

**Comment by victorandscience** [comment]
Some of the previous suggestions where a bit technical. I went ahead and reinstall my psi4 installation and created a new environment using `conda create -n p4env psi4`. 

While being on the environment. I am now getting the following error:
```---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-1aa65b575066> in <module>()
     11 #mol = qcel.models.Molecule.from_file("bent.xyz")
     12 
---> 13 mol = Molecule.from_file("bent.xyz")
     14 
     15 #Input as cartesian coordinates for linear water molecule

/anaconda3/lib/python3.6/site-packages/qcelemental/models/molecule.py in from_file(cls, filename, dtype, orient, **kwargs)
    609             raise KeyError("Dtype not understood '{}'.".format(dtype))
    610 
--> 611         return cls.from_data(data, dtype, orient=orient, **kwargs)
    612 
    613     ### Non-Pydantic internal functions

/anaconda3/lib/python3.6/site-packages/qcelemental/models/molecule.py in from_data(cls, data, dtype, orient, validate, **kwargs)
    538 
    539         if dtype in ["string", "psi4", "psi4+", "xyz", "xyz+"]:
--> 540             input_dict = to_schema(from_string(data)["qm"], dtype=2)
    541             validate = False  # Already validated, no need to do it twice
    542         elif dtype == "numpy":

KeyError: 'qm'
```

**Comment by loriab** [comment]
Yeah, we try to herd people along well-trod install paths because off them, the different install philosophies of Makefile and Python can lead to surprises. What are your following, please?

`python -c "import qcelemental as qc;print(qc.__file__, qc.__version__)"`
`python -c "import qcengine as qc;print(qc.__file__, qc.__version__)"`
`python -c "import psi4 as qc;print(qc.__file__, qc.__version__)"`

**Comment by victorandscience** [comment]
There was a problem with my environment. Lori helped me fix it. Thank you for your help too Levi!
