### ISSUE TITLE
Allow to skip test cases that download data

### ISSUE THREAD

**Issue by mbanck** [MolSSI/QCElemental#83]
Some build environments (like Ubuntu autobuilders) have internet firewalled off to ensure that the build process is self-contained. In cases like this, quite a few test cases seem to fail because they try to download stuff.

So it would be convenient if there was an option or switch to skip those tests.

**Comment by loriab** [comment]
I suppose that'll be the pubchem tests. Should be easy enough.

**Comment by mbanck** [comment]
whoa, do you ever sleep??

**Comment by dgasmith** [comment]
New testing decorator of:

```
import socket

def internet_connection():
    try:
        socket.create_connection(("www.google.com", 80))
        return True
    except OSError:
        return False

using_web = pytest.mark.skipif(internet_connection() is False, reason="Could not connect to the internet")
```

**Comment by mbanck** [comment]
sorry, I never tested that back then; I've now checked that the pytests pass fine on my notebook (once I install `certifi`), but on the Debian autobuilders (which disable networking) they still fail:

https://buildd.debian.org/status/fetch.php?pkg=qcelemental&arch=all&ver=0.17.0%2Bdfsg-2&stamp=1610282048&raw=0

E.g.:

```
>               raise URLError(err)
E               urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

/usr/lib/python3.9/urllib/request.py:1345: URLError
```

Is this expected, or have there been some regressions since  a4ebcca got committed?
